version: "3"
services:
    app:
        container_name: app
        restart: always
        build: .
        ports:
            - "8080:8080"
        links:
            - mongo
        volumes:
            - ./data:/data
            - ./logs:/logs
        env_file: ././.env
    mongo:
        container_name: db
        image: mongo
        ports:
            - "27017:27017"
        env_file: ././.env
